services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres16-4-alpine
    environment:
      POSTGRES_DB: dat09bot-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: